files:
  - source: /public/locales/en/hompage.json
    translation: /public/locales/%locale%/%original_file_name%.json
  - source: /public/locales/vi/hompage.json
    translation: '%original_path%/%original_file_name%.json'
