files:
  - source: /public/locales/en/hompage.json
    translation: /public/locales/%locale%/hompage.json
  - source: /public/locales/vi/hompage.json
    translation: /public/locales/%locale%/hompage.json
